name: Deploy Web app on port 8000

on:
  push:
    tags:
      - 'v*-beta'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'

    - name: Build and Publish API
      run: |
          cd web
          dotnet publish -c Release -o Release

    - name: List files
      run: |
          cd web
          cd Release
          ls -a

    - name: Login to docker hub
      run: |
          cd web
          sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build docker image
      run: |
          cd web
          sudo docker build -f Dockerfilewebdev -t ${{ secrets.DOCKER_USERNAME }}/release-monkey-web .

    - name: Publish image to Docker-hub
      run: |
          cd web
          sudo docker push ${{ secrets.DOCKER_USERNAME }}/release-monkey-web:latest

  deploy:
    needs: build
    runs-on: [dev-runner]
    steps:
      - name: Pull Image from docker hub
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/release-monkey-web:latest
      - name: Delete old container
        run: sudo docker rm -f release-monkey-web-container
      - name: Run docker container
        run: sudo docker run -d -p 8000:8000 --name release-monkey-web-container ${{ secrets.DOCKER_USERNAME }}/release-monkey-web
