name: Deploy Grad Server on port 5000

on:

  pull_request:
    # types:
    #   - closed
    branches:
      - main

jobs:
  build:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'

    - name: Build and Publish API
      run: |
          cd server
          dotnet publish -c Release -o Release

    - name: Update Release with .env
      run: |
          cd server
          echo "DB_HOST=${{secrets.DB_HOST_GRAD}}" > Release/.env
          echo "DB_USER=${{secrets.DB_GRAD_USERNAME}}" >> Release/.env
          echo "DB_PASS=${{secrets.DB_GRAD_PASSWORD }}" >> Release/.env
          echo "DB_NAME=release_monkey_db" >> Release/.env
          echo "DB_TRUST_CERT=true" >> Release/.env
          echo "GITHUB_APP_CLIENT_ID=${{secrets.HUB_APP_CLIENT_ID }}" >> Release/.env
          echo "GITHUB_APP_CLIENT_SECRET=${{secrets.HUB_APP_CLIENT_SECRET }}" >> Release/.env
          echo "SMTP_USERNAME=${{secrets.SMTP_USERNAME }}" >> Release/.env
          echo "SMTP_PASSWORD=${{secrets.SMTP_PASSWORD }}" >> Release/.env

    - name: List files
      run: |
          cd server
          cd Release
          ls -a

    - name: Login to docker hub
      run: |
          cd server
          sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build docker image
      run: |
          cd server
          sudo docker build -f Dockerfilegrad -t ${{ secrets.DOCKER_USERNAME }}/release-monkey-grad .

    - name: Publish image to Docker-hub
      run: |
          cd server
          sudo docker push ${{ secrets.DOCKER_USERNAME }}/release-monkey-grad:latest

  deploy:
    needs: build
    # if: github.event.pull_request.merged == true
    runs-on: [dev-runner]
    steps:
      - name: Pull Image from docker hub
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/release-monkey-grad:latest
      - name: Delete old container
        run: sudo docker rm -f release-monkey-grad-container
      - name: Run docker container
        run: sudo docker run -d -p 5000:5000 --name release-monkey-grad-container ${{ secrets.DOCKER_USERNAME }}/release-monkey-grad
