name: Flyway Migrations

on:

  pull_request:
    types:
      - closed
    branches:
      - main
  
env:
  FLYWAY_VERSION: 9.16.3

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Flyway
      run: |
        wget -qO- https://download.red-gate.com/maven/release/org/flywaydb/enterprise/flyway-commandline/${{ env.FLYWAY_VERSION }}/flyway-commandline-${{ env.FLYWAY_VERSION }}-linux-x64.tar.gz | tar -xvz && sudo ln -s `pwd`/flyway-${{ env.FLYWAY_VERSION }}/flyway /usr/local/bin 

    - name: Run Flyway Migrations
      env:
        FLYWAY_URL: ${{ secrets.DB_BUILD_URL}}
        FLYWAY_USER: ${{ secrets.DB_BUILD_USERNAME }}
        FLYWAY_PASSWORD: ${{ secrets.DB_BUILD_PASSWORD }}
      run: |
        flyway repair
        flyway info
        flyway migrate