name: Release

on:
  push:
    tags:
      - 'v*-prod'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Build CLI Windows
        working-directory: ./cli
        run: dotnet publish -r win-x64 -c Release --self-contained true

      - name: Build CLI Linux
        working-directory: ./cli
        run: dotnet publish -r linux-x64 -c Release --self-contained true

      - name: Mark Production Windows
        working-directory: ./cli/bin/Release/net8.0/win-x64/publish
        run: ren cli.exe rmk.exe

      - name: Mark Production Linux
        working-directory: ./cli/bin/Release/net8.0/linux-x64/publish
        run: ren cli rmk        

      - name: Upload Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: Release ${{ github.ref_name }}
          prerelease: false
          files: |
            cli/bin/Release/net8.0/win-x64/publish/*.exe
            cli/bin/Release/net8.0/linux-x64/publish/rmk
